function [electric_parameters] = calculateCircuitParamsStruct(DataSystem,VarSystem)
    inputStruct = struct(...
        'Us', 12,...
        'Ie', 1e-3,...
        'beta', DataSystem.Transistor.h21(VarSystem.IteratorTransistor),...
        'Ube', 0.55,...
        'f', 20,...
        't', VarSystem.t);
    electric_parameters = calculateCircuitParams(inputStruct);
end