function [electric_parameters] = calculateCircuitParamsStruct(DataSystem,VarSystem)
    % inputStruct = struct(...
    %     'Us', 12,...
    %     'Ie', 1e-3,...
    %     'beta', DataSystem.Transistor.h21(VarSystem.IteratorTransistor),...
    %     'Ube', 0.55,...
    %     'Rb', VarSystem.resistance_B,...
    %     'Rbe', VarSystem.resistance_BE,...
    %     'Re', VarSystem.resistance_E,...
    %     'f', 20,...
    %     't', VarSystem.t);
    % electric_parameters = calculateCircuitParams(inputStruct);

inputStruct = struct(...
    'Re', VarSystem.resistance_E, ...      % Значение резистора Re
    'Rbe', VarSystem.resistance_BE, ...     % Значение резистора Rbe
    'Rb', VarSystem.resistance_B, ...      % Значение резистора Rb
    'beta', DataSystem.Transistor.h21(VarSystem.IteratorTransistor), ...    % Бета (усиление тока биполярного транзистора)
    'f', 20, ...      % Частота в герцах
    't', VarSystem.t, ...      % Временной интервал
    'Us', 12, ...       % Напряжение источника
    'Ube', 0.7, ...      % Напряжение на переходе базы-эмиттера
    'h11', 5e3,...
    'h22', 22e3...
);

% Вызов функции
electric_parameters = calculateDirectCircuitParams(inputStruct);

end