function [lambda] = getReliabilityTransistor(CoefStruct)
    % lambda = lambdaB*kPr*kR*kF*kS1*kE;
    lambda = CoefStruct.Lambda_b * ...
        CoefStruct.kPr  *...
        CoefStruct.kR   *...
        CoefStruct.kF   *...
        CoefStruct.kS1  *...
        CoefStruct.kE   ;

end